openapi: 3.0.0
info:
  title: Order API
  description: API for managing orders
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /orders:
    get:
      summary: Get all orders
      responses:
        200:
          description: A list of all orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDto'
      parameters:
        - name: productId
          in: query
          description: ID of the product associated with the order
          required: true
          schema:
            type: string
        - name: email
          in: query
          description: Email of the person who placed the order
          required: true
          schema:
            type: string
      responses:
        200:
          description: The ID of the created order
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: string
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        productId:
          type: string
      required:
        - orderId
        - email
        - productId
    OrderDto:
      type: object
      properties:
        email:
          type: string
        productId:
          type: string
      required:
        - email
        - productId
